openapi: 3.0.0
info:
    title: Salon Blue API
    version: 1.0.0
    description: API for Salon Blue which is a salon appointment booking system.
servers:
    - url: http://localhost:5000
      description: development server
components:
    securitySchemes:
        BearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT

security:
    - BearerAuth: []

paths:
    /api/v1/auth/register:
        post:
            summary: Register a new user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                email:
                                    type: string
                                password:
                                    type: string
                                mobileNo:
                                    type: string
                                role:
                                    type: string
                responses:
                    "200":
                        description: User registered successfully
                    "400":
                        description: Bad request
                    "500":
                        description: Internal server error

    /api/v1/auth/login:
        post:
            summary: Login a user
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                email:
                                    type: string
                                password:
                                    type: string
                responses:
                    "200":
                        description: User logged in successfully
                    "400":
                        description: Bad request
                    "500":
                        description: Internal server error

    /api/v1/auth/me:
        get:
            summary: Get current user
            security:
                - BearerAuth: []
            parameters:
                - in: header
                  name: Authorization
                  required: true
                  schema:
                      type: string
                  description: Bearer token for authentication
            responses:
                "200":
                    description: User fetched successfully
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized - Token is missing or invalid
                "500":
                    description: Internal server error

    /api/v1/services:
        get:
            summary: Get all services
            security:
                - BearerAuth: []
            parameters:
                - in: header
                  name: Authorization
                  required: true
                  schema:
                      type: string
                  description: Bearer token for authentication
            responses:
                "200":
                    description: Services fetched successfully
                "400":
                    description: Bad request
                "401":
                    description: Unauthorized - Token is missing or invalid
                "500":
                    description: Internal server error

    /api/v1/services/add:
        post:
            summary: Add a new service
            security:
                - BearerAuth: []
            parameters:
                - in: header
                  name: Authorization
                  required: true
                  schema:
                      type: string
                  description: Bearer token for authentication
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                name:
                                    type: string
                                price:
                                    type: number
                                duration:
                                    type: number
                                serviceImageURL:
                                    type: string
                responses:
                    "200":
                        description: Service added successfully
                    "400":
                        description: Bad request
                    "401":
                        description: Unauthorized - Token is missing or invalid
                    "500":
                        description: Internal server error
